fullnameOverride: kps

alertmanager:
  enabled: false

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 128Mi

prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    retention: 7d
    retentionSize: 15GB
    scrapeInterval: 60s
    evaluationInterval: 60s
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 1280Mi
      limits:
        memory: 1280Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          storageClassName: local-path-retain
          resources:
            requests:
              storage: 20Gi

grafana:
  admin:
    existingSecret: grafana-admin
    userKey: admin-user
    passwordKey: admin-password
  defaultDashboardsTimezone: Asia/Ho_Chi_Minh
  persistence:
    enabled: true
    storageClassName: local-path-retain
    size: 2Gi
  ingress:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
    limits:
      memory: 2Gi
  env:
    GOGC: "50"
  grafana.ini:
    dataproxy:
      response_limit: "52428800"

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 128Mi
    limits:
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      memory: 64Mi
