sonar.projectKey=BaoDuong254_trellify
sonar.organization=baoduong254

sonar.projectName=trellify
sonar.projectVersion=1.6.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.d.ts,**/coverage/**,**/.turbo/**,**/playwright-report/**,**/test-results/**,**/*.spec.ts,**/*.spec.tsx,apps/server/test/**,apps/client/src/test/**,e2e/**

sonar.tests=.
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,apps/server/test/**,apps/client/src/test/**,e2e/**
sonar.javascript.lcov.reportPaths=apps/server/coverage/lcov.info,apps/client/coverage/lcov.info,packages/shared/coverage/lcov.info
