sonar.projectKey=BaoDuong254_trellify
sonar.organization=baoduong254

sonar.projectName=trellify
sonar.projectVersion=1.6.0

sonar.sources=.

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.d.ts,**/coverage/**,**/.turbo/**
