---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: observability
spec:
  encryptedData:
    bot-token: AgDoUQeGAi6MiAatMt3mkVvQY5wTQ9ecV0r0cZ/fme2cqPRFfKMQwRsK8jLAECfna5Uc5Kg+Bcpl+wfkR0y0N72sKoy++Fn3QgaTQlEuPzYul09ssBq+l0jPBkc0AfHHrfbe3QC37+5cZvrgL54hK10UfAs4zCLhHJxuKV8cW+2KQQuc1dpe78Z+nXF41dHe0ua86opBtixE27YXuTvrY/gdJDSh8aE6G7GiH1hxaJ2gQ/N+SiyiZXJgaVa8+UqPizqBafzEs5EHNcozf172OnQ3LOHasdl7JhHSr0ytY2eMn+o3Eh24Lb+RyN84heR4yN7f4BD6cVmeuiEjUDHD7IJJlZaMuUL6ZenN8CEFE5SowUJSTuuzGYsCO7HWCt6PCdS7rMfa91gEmF8UALqr5/q++wxbsUv868hmLD4qAtbqYlgwmpGO8MsP1yyctrdRTiNodjxzsHU9Qg1OxbGdP1/3N5sWhQlwH+aC9DUlq7k8EBgqQU9Ul5KxEvrVeTliKcFKzleQfHis8khAGtU9xW+Wfw9AfvRcnA+gXsanDcuEeq5kVREl2i8ZnzkSxqWT86VtxStoIioScrpZ0B3CneD1ikC3WbY2Qtl4l/pumJnJabsczbaK3LJCs/uZGY6lzqvEk3ys9Or6o/3sXwILMiH8/mUASWpyVPNkIQWwesorMhtnq0Es4HA1SQZpKi+9KfSIT+lomSqoH+oRtqDTRH7YeSDDId7JxjRqa8UOpK/KkON+49r0H54OxHVmX08r
    chat-id: AgBbbtxNMCVSLz9Qck28sLXE6e+uiZ572HiGgXpbGx9c6NdKIPRgpfPHmT0HHTVLZSrC+OzDdkXg3OoZbpVlf8ec/WUh7Gka+l0pcnYo8t8hCl7SCrHcrmt5BVaqE/8qF4UeXpnBV0IJYNEUsrNANEGCt2KeX/fgNNYnxGZjDiCcUlpEjWRMbOPml3uB3eEgFaHqc8LJW8ulkbyBQBaP+NwPzZ9Rmx0mMOqFKLvP24jHbPz/fJWBfZZSo+2kNEeCDbTwDMX/7kkWBNdGAamv2GWY++lfdZG8+EL+oJVg87jYLRuPiFpbKmSoiDXMWFF+L08gOkuD28ZEaJt7WV3yIiNNnn1NmJ03gPK3H42i0GzzT/XdZBB9vXmdOJu7L2Ux1vNPd8jGP9llirPpewJSwUWp2/eAeMxJtjj3LS/MXFuwds+mdtM2T5qP5cCgMiXz8vC3lRi7STrx7ve3baOm0BoEHvO8W34RC0Tb2jvGASFKbDK/3xHu7pXnDRhKQUIR6thIcaJcPRY+QBy/vfChKi3kXCwKsDYwE4JDf0MstzxXUdJkmow46m48aCNFyPw0/Vy/gvrC5Uoca7TIkCtDlouzmVT0WjQrbW5vrB5R6DjIRRSIMRLLDD2jdlW+8O/td8YCo1+A4+ZrwVNtr/ylaTGsq5h9xmVUvrmmLkfcexQ5mHgIrOmxhOpEFPa7uANIzhH1nHGWEPccJBWh
  template:
    metadata:
      name: alertmanager-telegram
      namespace: observability
