---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgDK6rGGhR63mJKbgiJXIgzzEnVXD3AUJuVbs70LEkEPzV9OCHiA1Vy4miHNe3EfVt6OOSW0sfedPDgsYH0ODihebjL6XpIIVTEBQJT9D/Dd2KCMs2qVTPJKaG67iuTMW8a4IjvoVQZlUvkrq2novztBgCtfUYHtMyCNksITaSXkNme3K/lmnCpVu6Cweb+XhtEwBfNPHxvtjeW9/q/b+gyi17JK60WGDca+HCE1vUQCppuXKyQ5je8cODPPU4ctQm0wqeq0robWzIZd4rH/R3nm9G/wYZDEZineC1fDLzTCaEspAuV2+oVcLgH17Q020+XYjrrk21wvhVs+HCdihPN7M8NBRJGZP3ktlH1Eh3VJWJTtpNNsgnVUtzqccX5Ll6uWVyoo6CMIP8b8l7YJyjPDHUrj33T85KAJYMG2sR3UWOpE9foMTbqSw/Zbzve23bY419dFuyiaRbo9w4NRdginlhBeisJBsF3kpJqvGmlZKjG5Lkcu7iJxzwF8ziuVTk9UPAyIUmztGhoBK3nzA40tcPXgCHy8dNM2bgnblisUOLuwtLW+YW4GSjtpI4VvIgwynbQ9hCLUxmIdK2HTdIwAMLh1t5N6oywC1BQ5Sbq1iAR0eXsXFUpMKJKDJvwyDrNZCKtJsLPnSYtvu7HSOGMU4ZGbm4z+zUUxr8crjRfM656eY3QSdVwgqk/Hzt0mUyouie8CjTQLiC2fZV3Wl8k14Cqx8AP/gec=
    admin-user: AgCgEGBVNS8jpE2ljv1jx9XRS63CoVLXsx+CGt6Xl7xutuMbo2KsVcOe3j3Z5U/u9YWSYcbA15R5mWhEV6ScmNRf+GU//fXm0gcikhVII/cgzM0AUTNFSI9ndn/S1Y0Biwb4C6qcki6RUmeHMNcll3qV1jft30V0ohaoVIFrXvL5sXy3YaGURS/bCSuRawA59Y1ivtWl7u1EplPubEzScAjCCZWpQ/B86dpWgRB425koR1SEaqCVNqBlLltYvWfZQx4fv1ASzXRl1xcQ744kqhoWcelpOHAFgG4EourXrUE7u9eKFCKyq+hBksg6LSvjPPwUko1Ey7yj4jIGH+lHmc8C+I+HgOsSb9ipQmP4mIGZCj5NbumFw58Trc70wH03NJGdTlSEfsKsn74138+Y1DI6QNMEQ/otdHWJQ5dCuJ66i2tuyPw2D7wGFXs1ZN3f48545Hvvo/Ch2E5BaXjAqhziFJrO73uNtj4mbGXis0WUQor1gUia1sDbJlRV0POwH2wonKxPcEpdyukwdhK6i2I4v/NA86oXKiK4k4Qg/IoPvqKuvVbb1/aZymg7Qt2QcN5ZuZPOLT/B/mdF0mMOkcUsL21nQ6NuwdR00qx1KMzG7qzFxrvra9RAAyyjuq4zuDiMEDsU1GtPVF6YI/OUE1W+L/juM7QDGWy+SZ7DUNdbTdRSSdQMCMR7OFbNYwjw1Nc5X9kHrg==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
