apiVersion: v1
kind: ConfigMap
metadata:
  name: trellify-server-config
data:
  PORT: "3000"
  NODE_ENV: "production"
  CLIENT_URL: "https://trellify.duonggiabao.com"
  QUEUE_PREFIX: "trellify"
  WORKER_CONCURRENCY: "5"
  WORKER_HEALTH_PORT: "3001"
  METRICS_PORT: "9464"
  CACHE_ENABLED: "true"
  CACHE_COMMAND_TIMEOUT_MS: "1000"
  BOARD_CACHE_TTL_SECONDS: "30"
  BOARD_CACHE_NEGATIVE_TTL_SECONDS: "15"
  BOARD_MEMBERSHIP_CACHE_TTL_SECONDS: "5"
  BLOOM_FILTER_ENABLED: "true"
  REDIS_COMMAND_TIMEOUT_MS: "2000"
  DATABASE_NAME: "trellify"
  ADMIN_EMAIL_ADDRESS: "duonggiabao254@gmail.com"
  ADMIN_EMAIL_NAME: "Trellify Team"
  ACCESS_TOKEN_LIFE: "1h"
  REFRESH_TOKEN_LIFE: "14d"
  COOKIE_MAX_AGE: "14d"
  CLOUDINARY_CLOUD_NAME: "dvvfq0j8u"
