apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trellify

resources:
  - namespace.yaml
  - configmap-server.yaml
  - deployment-server.yaml
  - deployment-worker.yaml
  - deployment-client.yaml
  - services.yaml
  - ingress.yaml
  - pdb.yaml
  - hpa-server.yaml
  - networkpolicy.yaml
  - servicemonitor.yaml
  - redis/configmap.yaml
  - redis/statefulset.yaml
  - redis/services.yaml
  - mongodb/init-configmap.yaml
  - mongodb/statefulset.yaml
  - mongodb/services.yaml
  - mongodb/backup-cronjob.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: trellify
    includeSelectors: false
