apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingress-nginx
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.15.1
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/infra/ingress-nginx/values.yaml
    - repoURL: https://github.com/BaoDuong254/trellify.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
