apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-sealed-secrets
  namespace: argocd
spec:
  project: platform
  sources:
    - repoURL: https://bitnami.github.io/sealed-secrets
      chart: sealed-secrets
      targetRevision: 2.19.2
      helm:
        releaseName: sealed-secrets
        valueFiles:
          - $values/infra/sealed-secrets/values.yaml
    - repoURL: https://github.com/BaoDuong254/trellify.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
