---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: trellify-redis-auth
  namespace: trellify
spec:
  encryptedData:
    password: AgBTNf/YiCngQGXZ9/xixmUqCoOYZBmBCjOHQ7oVbriKyaDghsPo3nLRTUwCxfqTcnzWzhA7GPPNsuXbvTkoXhW/3QdymTlcdTV8y3DSptybUpU73xPxEHh1hO7LGI18pfK+jY/A1C7JH+EPbKKPNbgfQvKKgNBh+yAfYQmLOGUnOnaGALMPWYGHh3aDzNWeeq2No9hR32kHjsmkZIB64tRrVpdwp5KO5F+guzUT2V0R2P+CAI44u31Xt3qiM+ApQ460dNlM3xUoTFQrXGYz9L0glDz8D/SpOVSNo7KKvk0Zb2F5vpn1h0EtQBHc/MYWJhdtMNryK+KpQEEJ6BGap1Rz0d/OLu5dijkCpJP9RuVr1ZS9VoGbEvZw6R6RpgOIleYyvlQy2AaBg1aqxxSzXNyUsjkkAgfNxESKNFJ1z+aWQDK71lbzXUTAmNO6OFzRJ5CUzoJzwsVOEpMgoM6vgoHymYd6HnSlL9pCa0Y9gN5XhYefU4CEles1L6m8N3QhGtdbcM+lUMsfhuDf3ZTVhgjBpRkLfs7/s4f61mzPYa0Sm/9mIgTTUrUFa0lrZfuCT6KpuMV9JOWWlmgRulyxZ//qdL7YGPyrzP5gH/79NvULL7lti4P8nL68Mk1CEHqgSXFmzAzJ5MyIxe7TytYXhDwB5mTA+jqZcpHOmK4kEroFUn1rUn/jnIjzJy7IoFu/R34e0kGlIx9o5iPKOFcd7ons1LLY54/DNHki7fKhZa4CgA==
  template:
    metadata:
      name: trellify-redis-auth
      namespace: trellify
