apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: b14acf31-55ab-4582-99cc-6a4b28e32d1c
    credentials-file: /etc/cloudflared/creds/credentials.json

    metrics: 0.0.0.0:2000
    no-autoupdate: true

    protocol: quic

    ingress:
      - hostname: "*.duonggiabao.com"
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
        originRequest:
          connectTimeout: 10s

      - hostname: "duonggiabao.com"
        service: http://ingress-nginx-controller.ingress-nginx.svc.cluster.local:80
        originRequest:
          connectTimeout: 10s

      - service: http_status:404
