---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgDZGD13G/gUuwsCQ5kANJDkjbBxsQv47wpYDu5UrLpUmL6MXZNQi9KP5iWi1T8YCyuRcCEGQ/JmuyX6pCx6F6cW3QBZg2i+TlQTalZVcUuN9EW2Yxt+0mdiYT2hUqUs0Gb5H3JUonFdE+GxUebJ02IICL1BpyoKVp7Mu80pteCysorLcQJywE+1ELSw1mvcEVoAnvW7f4KjEVzUxWmVAiWJNa7m7M+KJ1WUGbfOHIv4drFSpkC9jmFyl9FpnqeRp5OADCm5zCcIkQMP3FGZ3xjKSck/XxmRlevkanIV/rIVpHl+6EaMzaejwKBDSKIi1cDvGHkZEeKdjSLrD5Czd7jnbrLuQVeSqBeufy/lwJOhwfeeUC/hHrG4DaRykUgsUpW8ZECVeCenArjnqCJMVx738DBV+UfwjmaGiLLs99Qqxxi2oZ6KFDz1SuItuv+UVgziAJxWQO5+0P1ufyNmQHoyFznjbfZRfFthKKAky0zh3sVQscE2x46ErprM+J0/gS22yAytH/rsJUEawMguabAqeBegqmYe3PgdPZqKnDttpIPPjtPqq75n1sBVCF+xNdLjKNHQHB7ISbeBgJkVY8F7MihjOChQmbru4nqnhq7SYEot0QOhCktSzKCfStBLD+xxeM4Bgab5/P6kR1wlB/lVm1dJzy46kjq+mlrDO+Ea/g73Zi9Ed+jsSICqg5ANYNYLCOU7ot7wvrMO+Nv5SgVyJJcd2JOzB3x9+fA5qE/ruC1a9Ps3wZ/sjcqyFodF121UrKS7x00/ce/o+5Mo0GwjdaVC4Hvu9MRfbQhSMPVdBKdzgbhIbAlfH/u+an2swReBc6vrXxtpI+B4RjvlFONpmkNp9xJED4a2AMIehtgKrkY/NZvYp60RpYdYL0jUCv+bGyAz70Eaa8OfQLecM58xLRTyhy9/gOk5jZoehfM4
  template:
    metadata:
      name: cloudflared-credentials
      namespace: cloudflared
